sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t foreverithd/perrn-react-tst -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true foreverithd/perrn-react-tst npm test

after_success:
  - docker build -t foreverithd/perrn-client ./client
  - docker build -t foreverithd/perrn-nginx ./nginx
  - docker build -t foreverithd/perrn-server ./server
  - docker build -t foreverithd/perrn-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push foreverithd/perrn-client
  - docker push foreverithd/perrn-nginx
  - docker push foreverithd/perrn-server
  - docker push foreverithd/perrn-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "perrn"
  env: "Perrn-env-2"
  bucket_name: "elasticbeanstalk-ap-south-1-824192598227"
  bucket_path: "perrn-bucket"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY